export default [
    'calc',
    'cubic-bezier',
    'linear-gradient',
    'rgba',
    'url',
    'blur',
    'translate',
    'rotate',
    'translateY',
    'translateX',
    'attr',
    'scale',
    'translate3d',
    'translateZ',
    'scale3d',
];
